export enum EventType {
  'CREATE_TASK' = 'CREATE_TASK',
  'DELETE_TASK' = 'DELETE_TASK',
  'INSERT_TITLE' = 'INSERT_TITLE',
  'DELETE_TITLE' = 'DELETE_TITLE',
  'UPDATE_POSITION' = 'UPDATE_POSITION',
}
