/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as SignupImport } from './routes/signup';
import { Route as LoginImport } from './routes/login';
import { Route as AuthImport } from './routes/_auth';
import { Route as IndexImport } from './routes/index';
import { Route as AuthAccountImport } from './routes/_auth.account';
import { Route as AuthProjectImport } from './routes/_auth.$project';
import { Route as AuthAccountIndexImport } from './routes/_auth.account.index';
import { Route as AuthProjectIndexImport } from './routes/_auth.$project.index';
import { Route as AuthAccountSettingsImport } from './routes/_auth.account.settings';
import { Route as AuthProjectSettingsImport } from './routes/_auth.$project.settings';
import { Route as AuthProjectBoardImport } from './routes/_auth.$project.board';
import { Route as AuthProjectSettingsIndexImport } from './routes/_auth.$project.settings.index';
import { Route as AuthProjectSettingsSprintsImport } from './routes/_auth.$project.settings.sprints';
import { Route as AuthProjectSettingsLabelsImport } from './routes/_auth.$project.settings.labels';
import { Route as AuthProjectBoardTaskImport } from './routes/_auth.$project.board.$task';

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any);

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const AuthAccountRoute = AuthAccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthRoute,
} as any);

const AuthProjectRoute = AuthProjectImport.update({
  id: '/$project',
  path: '/$project',
  getParentRoute: () => AuthRoute,
} as any);

const AuthAccountIndexRoute = AuthAccountIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAccountRoute,
} as any);

const AuthProjectIndexRoute = AuthProjectIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthProjectRoute,
} as any);

const AuthAccountSettingsRoute = AuthAccountSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthAccountRoute,
} as any);

const AuthProjectSettingsRoute = AuthProjectSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthProjectRoute,
} as any);

const AuthProjectBoardRoute = AuthProjectBoardImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AuthProjectRoute,
} as any);

const AuthProjectSettingsIndexRoute = AuthProjectSettingsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthProjectSettingsRoute,
} as any);

const AuthProjectSettingsSprintsRoute = AuthProjectSettingsSprintsImport.update({
  id: '/sprints',
  path: '/sprints',
  getParentRoute: () => AuthProjectSettingsRoute,
} as any);

const AuthProjectSettingsLabelsRoute = AuthProjectSettingsLabelsImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AuthProjectSettingsRoute,
} as any);

const AuthProjectBoardTaskRoute = AuthProjectBoardTaskImport.update({
  id: '/$task',
  path: '/$task',
  getParentRoute: () => AuthProjectBoardRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_auth': {
      id: '/_auth';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AuthImport;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    '/signup': {
      id: '/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof SignupImport;
      parentRoute: typeof rootRoute;
    };
    '/_auth/$project': {
      id: '/_auth/$project';
      path: '/$project';
      fullPath: '/$project';
      preLoaderRoute: typeof AuthProjectImport;
      parentRoute: typeof AuthImport;
    };
    '/_auth/account': {
      id: '/_auth/account';
      path: '/account';
      fullPath: '/account';
      preLoaderRoute: typeof AuthAccountImport;
      parentRoute: typeof AuthImport;
    };
    '/_auth/$project/board': {
      id: '/_auth/$project/board';
      path: '/board';
      fullPath: '/$project/board';
      preLoaderRoute: typeof AuthProjectBoardImport;
      parentRoute: typeof AuthProjectImport;
    };
    '/_auth/$project/settings': {
      id: '/_auth/$project/settings';
      path: '/settings';
      fullPath: '/$project/settings';
      preLoaderRoute: typeof AuthProjectSettingsImport;
      parentRoute: typeof AuthProjectImport;
    };
    '/_auth/account/settings': {
      id: '/_auth/account/settings';
      path: '/settings';
      fullPath: '/account/settings';
      preLoaderRoute: typeof AuthAccountSettingsImport;
      parentRoute: typeof AuthAccountImport;
    };
    '/_auth/$project/': {
      id: '/_auth/$project/';
      path: '/';
      fullPath: '/$project/';
      preLoaderRoute: typeof AuthProjectIndexImport;
      parentRoute: typeof AuthProjectImport;
    };
    '/_auth/account/': {
      id: '/_auth/account/';
      path: '/';
      fullPath: '/account/';
      preLoaderRoute: typeof AuthAccountIndexImport;
      parentRoute: typeof AuthAccountImport;
    };
    '/_auth/$project/board/$task': {
      id: '/_auth/$project/board/$task';
      path: '/$task';
      fullPath: '/$project/board/$task';
      preLoaderRoute: typeof AuthProjectBoardTaskImport;
      parentRoute: typeof AuthProjectBoardImport;
    };
    '/_auth/$project/settings/labels': {
      id: '/_auth/$project/settings/labels';
      path: '/labels';
      fullPath: '/$project/settings/labels';
      preLoaderRoute: typeof AuthProjectSettingsLabelsImport;
      parentRoute: typeof AuthProjectSettingsImport;
    };
    '/_auth/$project/settings/sprints': {
      id: '/_auth/$project/settings/sprints';
      path: '/sprints';
      fullPath: '/$project/settings/sprints';
      preLoaderRoute: typeof AuthProjectSettingsSprintsImport;
      parentRoute: typeof AuthProjectSettingsImport;
    };
    '/_auth/$project/settings/': {
      id: '/_auth/$project/settings/';
      path: '/';
      fullPath: '/$project/settings/';
      preLoaderRoute: typeof AuthProjectSettingsIndexImport;
      parentRoute: typeof AuthProjectSettingsImport;
    };
  }
}

// Create and export the route tree

interface AuthProjectBoardRouteChildren {
  AuthProjectBoardTaskRoute: typeof AuthProjectBoardTaskRoute;
}

const AuthProjectBoardRouteChildren: AuthProjectBoardRouteChildren = {
  AuthProjectBoardTaskRoute: AuthProjectBoardTaskRoute,
};

const AuthProjectBoardRouteWithChildren = AuthProjectBoardRoute._addFileChildren(
  AuthProjectBoardRouteChildren
);

interface AuthProjectSettingsRouteChildren {
  AuthProjectSettingsLabelsRoute: typeof AuthProjectSettingsLabelsRoute;
  AuthProjectSettingsSprintsRoute: typeof AuthProjectSettingsSprintsRoute;
  AuthProjectSettingsIndexRoute: typeof AuthProjectSettingsIndexRoute;
}

const AuthProjectSettingsRouteChildren: AuthProjectSettingsRouteChildren = {
  AuthProjectSettingsLabelsRoute: AuthProjectSettingsLabelsRoute,
  AuthProjectSettingsSprintsRoute: AuthProjectSettingsSprintsRoute,
  AuthProjectSettingsIndexRoute: AuthProjectSettingsIndexRoute,
};

const AuthProjectSettingsRouteWithChildren = AuthProjectSettingsRoute._addFileChildren(
  AuthProjectSettingsRouteChildren
);

interface AuthProjectRouteChildren {
  AuthProjectBoardRoute: typeof AuthProjectBoardRouteWithChildren;
  AuthProjectSettingsRoute: typeof AuthProjectSettingsRouteWithChildren;
  AuthProjectIndexRoute: typeof AuthProjectIndexRoute;
}

const AuthProjectRouteChildren: AuthProjectRouteChildren = {
  AuthProjectBoardRoute: AuthProjectBoardRouteWithChildren,
  AuthProjectSettingsRoute: AuthProjectSettingsRouteWithChildren,
  AuthProjectIndexRoute: AuthProjectIndexRoute,
};

const AuthProjectRouteWithChildren = AuthProjectRoute._addFileChildren(AuthProjectRouteChildren);

interface AuthAccountRouteChildren {
  AuthAccountSettingsRoute: typeof AuthAccountSettingsRoute;
  AuthAccountIndexRoute: typeof AuthAccountIndexRoute;
}

const AuthAccountRouteChildren: AuthAccountRouteChildren = {
  AuthAccountSettingsRoute: AuthAccountSettingsRoute,
  AuthAccountIndexRoute: AuthAccountIndexRoute,
};

const AuthAccountRouteWithChildren = AuthAccountRoute._addFileChildren(AuthAccountRouteChildren);

interface AuthRouteChildren {
  AuthProjectRoute: typeof AuthProjectRouteWithChildren;
  AuthAccountRoute: typeof AuthAccountRouteWithChildren;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthProjectRoute: AuthProjectRouteWithChildren,
  AuthAccountRoute: AuthAccountRouteWithChildren,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '': typeof AuthRouteWithChildren;
  '/login': typeof LoginRoute;
  '/signup': typeof SignupRoute;
  '/$project': typeof AuthProjectRouteWithChildren;
  '/account': typeof AuthAccountRouteWithChildren;
  '/$project/board': typeof AuthProjectBoardRouteWithChildren;
  '/$project/settings': typeof AuthProjectSettingsRouteWithChildren;
  '/account/settings': typeof AuthAccountSettingsRoute;
  '/$project/': typeof AuthProjectIndexRoute;
  '/account/': typeof AuthAccountIndexRoute;
  '/$project/board/$task': typeof AuthProjectBoardTaskRoute;
  '/$project/settings/labels': typeof AuthProjectSettingsLabelsRoute;
  '/$project/settings/sprints': typeof AuthProjectSettingsSprintsRoute;
  '/$project/settings/': typeof AuthProjectSettingsIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '': typeof AuthRouteWithChildren;
  '/login': typeof LoginRoute;
  '/signup': typeof SignupRoute;
  '/$project/board': typeof AuthProjectBoardRouteWithChildren;
  '/account/settings': typeof AuthAccountSettingsRoute;
  '/$project': typeof AuthProjectIndexRoute;
  '/account': typeof AuthAccountIndexRoute;
  '/$project/board/$task': typeof AuthProjectBoardTaskRoute;
  '/$project/settings/labels': typeof AuthProjectSettingsLabelsRoute;
  '/$project/settings/sprints': typeof AuthProjectSettingsSprintsRoute;
  '/$project/settings': typeof AuthProjectSettingsIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/_auth': typeof AuthRouteWithChildren;
  '/login': typeof LoginRoute;
  '/signup': typeof SignupRoute;
  '/_auth/$project': typeof AuthProjectRouteWithChildren;
  '/_auth/account': typeof AuthAccountRouteWithChildren;
  '/_auth/$project/board': typeof AuthProjectBoardRouteWithChildren;
  '/_auth/$project/settings': typeof AuthProjectSettingsRouteWithChildren;
  '/_auth/account/settings': typeof AuthAccountSettingsRoute;
  '/_auth/$project/': typeof AuthProjectIndexRoute;
  '/_auth/account/': typeof AuthAccountIndexRoute;
  '/_auth/$project/board/$task': typeof AuthProjectBoardTaskRoute;
  '/_auth/$project/settings/labels': typeof AuthProjectSettingsLabelsRoute;
  '/_auth/$project/settings/sprints': typeof AuthProjectSettingsSprintsRoute;
  '/_auth/$project/settings/': typeof AuthProjectSettingsIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/signup'
    | '/$project'
    | '/account'
    | '/$project/board'
    | '/$project/settings'
    | '/account/settings'
    | '/$project/'
    | '/account/'
    | '/$project/board/$task'
    | '/$project/settings/labels'
    | '/$project/settings/sprints'
    | '/$project/settings/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | ''
    | '/login'
    | '/signup'
    | '/$project/board'
    | '/account/settings'
    | '/$project'
    | '/account'
    | '/$project/board/$task'
    | '/$project/settings/labels'
    | '/$project/settings/sprints'
    | '/$project/settings';
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/signup'
    | '/_auth/$project'
    | '/_auth/account'
    | '/_auth/$project/board'
    | '/_auth/$project/settings'
    | '/_auth/account/settings'
    | '/_auth/$project/'
    | '/_auth/account/'
    | '/_auth/$project/board/$task'
    | '/_auth/$project/settings/labels'
    | '/_auth/$project/settings/sprints'
    | '/_auth/$project/settings/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  SignupRoute: typeof SignupRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/$project",
        "/_auth/account"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_auth/$project": {
      "filePath": "_auth.$project.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/$project/board",
        "/_auth/$project/settings",
        "/_auth/$project/"
      ]
    },
    "/_auth/account": {
      "filePath": "_auth.account.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/account/settings",
        "/_auth/account/"
      ]
    },
    "/_auth/$project/board": {
      "filePath": "_auth.$project.board.tsx",
      "parent": "/_auth/$project",
      "children": [
        "/_auth/$project/board/$task"
      ]
    },
    "/_auth/$project/settings": {
      "filePath": "_auth.$project.settings.tsx",
      "parent": "/_auth/$project",
      "children": [
        "/_auth/$project/settings/labels",
        "/_auth/$project/settings/sprints",
        "/_auth/$project/settings/"
      ]
    },
    "/_auth/account/settings": {
      "filePath": "_auth.account.settings.tsx",
      "parent": "/_auth/account"
    },
    "/_auth/$project/": {
      "filePath": "_auth.$project.index.tsx",
      "parent": "/_auth/$project"
    },
    "/_auth/account/": {
      "filePath": "_auth.account.index.tsx",
      "parent": "/_auth/account"
    },
    "/_auth/$project/board/$task": {
      "filePath": "_auth.$project.board.$task.tsx",
      "parent": "/_auth/$project/board"
    },
    "/_auth/$project/settings/labels": {
      "filePath": "_auth.$project.settings.labels.tsx",
      "parent": "/_auth/$project/settings"
    },
    "/_auth/$project/settings/sprints": {
      "filePath": "_auth.$project.settings.sprints.tsx",
      "parent": "/_auth/$project/settings"
    },
    "/_auth/$project/settings/": {
      "filePath": "_auth.$project.settings.index.tsx",
      "parent": "/_auth/$project/settings"
    }
  }
}
ROUTE_MANIFEST_END */
