export enum EventType {
  'CREATE_TASK' = 'CREATE_TASK',
  'DELETE_TASK' = 'DELETE_TASK',
  'INSERT_TITLE' = 'INSERT_TITLE',
  'DELETE_TITLE' = 'DELETE_TITLE',
  'UPDATE_POSITION' = 'UPDATE_POSITION',

  'TASK_CREATED' = 'TASK_CREATED',
  'TASK_DELETED' = 'TASK_DELETED',
  'TITLE_INSERTED' = 'TITLE_INSERTED',
  'TITLE_DELETED' = 'TITLE_DELETED',
  'POSITION_UPDATED' = 'POSITION_UPDATED',
  'LABELS_CHANGED' = 'LABELS_CHANGED',
  'ASSIGNEES_CHANGED' = 'ASSIGNEES_CHANGED',
  'SUBTASK_CHANGED' = 'SUBTASK_CHANGED',
}
